"""
bots/advisor_reasoning.py
Generates real investment thesis from actual research data.
"""
import argparse, json, sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


def generate_reasoning(research: dict, model: Optional[dict] = None, earnings: Optional[dict] = None) -> dict:
    ticker = research.get("ticker", "") or research.get("key_metrics", {}).get("ticker", "UNKNOWN")
    rec = research.get("recommendation", "HOLD")
    conf = research.get("confidence", 0)
    strategy = research.get("strategy", "GROWTH")
    metrics = research.get("key_metrics", {})
    reasons = research.get("reasons", [])
    warnings = research.get("warnings", [])
    signals = research.get("signals", [])
    sentiment = research.get("sentiment", {})
    news = research.get("news", [])

    lines = []
    lines.append(f"## {ticker} Investment Thesis")
    lines.append("")
    lines.append(f"**Recommendation:** {rec} ({conf}% confidence)")
    lines.append(f"**Strategy:** {strategy}")
    lines.append(f"**Price:** ${metrics.get('current_price', 'N/A')}")
    if metrics.get('day_change_pct') is not None:
        d = metrics['day_change_pct']
        emoji = "🟢" if d > 0 else "🔴"
        lines.append(f"**Daily Change:** {emoji} {d:+.2f}%")
    lines.append("")

    # Valuation context
    if model:
        lines.append(f"**Valuation:** Target ${model.get('blended_target', 'N/A')} | "
                     f"Upside {model.get('upside_pct', 'N/A')}% | "
                     f"MoS {model.get('margin_of_safety_pct', 'N/A')}% | "
                     f"Verdict: {model.get('verdict', 'N/A')}")
        lines.append("")

    # Earnings context
    if earnings:
        lines.append(f"**Earnings:** {earnings.get('verdict', 'N/A')} (catalyst {earnings.get('earnings_catalyst_score', 0)})")
        if earnings.get('next_earnings_date'):
            days = earnings.get('days_to_earnings')
            if days is not None:
                lines.append(f"**Next Earnings:** {earnings['next_earnings_date']} ({days} days)")
            else:
                lines.append(f"**Next Earnings:** {earnings['next_earnings_date']}")
        lines.append("")

    # Key signals
    lines.append("### Technical Signals")
    for s in signals[:8]:
        score = s.get("score", 0)
        emoji = "✅" if score > 0 else "⚠️" if score < 0 else "➖"
        lines.append(f"{emoji} **{s.get('name', '').replace('_', ' ').title()}:** {s.get('note', '')}")
    lines.append("")

    # Bullish reasons
    if reasons:
        lines.append("### Positive Factors")
        for r in reasons[:5]:
            lines.append(f"✅ {r}")
        lines.append("")

    # Warnings
    if warnings:
        lines.append("### Risk Factors")
        for w in warnings[:5]:
            lines.append(f"⚠️ {w}")
        lines.append("")

    # Sentiment
    if sentiment:
        lines.append(f"### News Sentiment: {sentiment.get('label', 'NEUTRAL')} ({sentiment.get('score', 0)})")
        if sentiment.get('bullish'):
            lines.append(f"- {sentiment['bullish']} bullish mentions, {sentiment.get('bearish', 0)} bearish")
        if news[:3]:
            lines.append("- Recent headlines:")
            for n in news[:3]:
                lines.append(f"  - {n.get('title', '')}")
        lines.append("")

    # Core metrics
    lines.append("### Key Metrics")
    for k, v in [
        ("Ticker", ticker),
        ("Price", f"${metrics.get('current_price')}"),
        ("P/E (trailing)", metrics.get('pe_trailing')),
        ("P/E (forward)", metrics.get('pe_forward')),
        ("PEG", metrics.get('peg_ratio')),
        ("RSI(14)", metrics.get('rsi_14')),
        ("SMA 20", metrics.get('sma_20')),
        ("SMA 50", metrics.get('sma_50')),
        ("52W Range", f"${metrics.get('52_week_low')} - ${metrics.get('52_week_high')}" if metrics.get('52_week_low') else None),
        ("1mo Return", f"{metrics.get('return_1mo_pct')}%"),
        ("3mo Return", f"{metrics.get('return_3mo_pct')}%"),
        ("Volume Surge", metrics.get('volume_surge')),
        ("Market Cap", f"${metrics.get('market_cap', 0)/1e9:.1f}B" if metrics.get('market_cap') else None),
    ]:
        if v is not None:
            lines.append(f"- **{k}:** {v}")
    lines.append("")

    lines.append("---")
    lines.append("*Auto-generated by Stock Command Center. Not investment advice.*")

    reasoning_text = "\n".join(lines)
    return {
        "ticker": ticker,
        "recommendation": rec,
        "confidence": conf,
        "strategy": strategy,
        "reasoning": reasoning_text,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }


def run(args) -> bool:
    def _load(path):
        p = Path(path)
        if p.exists():
            with open(p, "r", encoding="utf-8") as f:
                return json.load(f)
        return {}

    research = _load(args.research)
    model = _load(args.model) if args.model else {}
    earnings = _load(args.earnings) if args.earnings else {}

    data = generate_reasoning(research, model or None, earnings or None)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)

    print(f"Advisor reasoning for {data['ticker']}: {data['recommendation']} ({data['confidence']}%)")
    return True


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--research", required=True)
    p.add_argument("--model", default="")
    p.add_argument("--earnings", default="")
    p.add_argument("--output", required=True)
    args = p.parse_args()
    sys.exit(0 if run(args) else 1)
