"""
bots/pitchbook_generator.py
Auto-generates markdown investment memos.
Usage: python bots/pitchbook_generator.py --ticker NVDA --research dashboard/data/output/ID.json --earnings dashboard/data/earnings/NVDA.json --model dashboard/data/models/NVDA.json --kyc dashboard/data/kyc/NVDA.json --output dashboard/data/pitchbooks/NVDA.md
"""
import argparse, json, sys
from datetime import datetime, timezone
from pathlib import Path


def generate_pitchbook(ticker: str, research: dict, earnings: dict, model: dict, kyc: dict) -> str:
    rec = research.get("recommendation", "HOLD")
    conf = research.get("confidence", 50)
    summary = research.get("summary", "")
    metrics = research.get("key_metrics", {})
    
    # Earnings section
    e_verdict = earnings.get("verdict", "N/A")
    e_score = earnings.get("earnings_catalyst_score", 0)
    e_history = earnings.get("earnings_history", [])
    
    # Model section
    m_target = model.get("blended_target", "N/A")
    m_mos = model.get("margin_of_safety_pct", 0)
    m_verdict = model.get("verdict", "N/A")
    dcf = model.get("dcf_model", {})
    comps = model.get("comparable_model", {})
    
    # KYC
    ky = kyc.get("risk_level", "UNKNOWN")
    k_score = kyc.get("compliance_score", 0)
    k_flags = kyc.get("flags", [])
    
    # Strategy tag
    strategy = "GROWTH"
    if "dcf" in str(m_target).lower() or m_mos > 15:
        strategy = "VALUE"
    elif e_score > 60:
        strategy = "MOMENTUM"
    elif k_score > 80 and conf > 70:
        strategy = "QUALITY"
    
    lines = [
        f"# Investment Memo: {ticker.upper()}",
        f"",
        f"**Recommendation:** {rec}  ",
        f"**Confidence:** {conf}%  ",
        f"**Strategy:** {strategy}  ",
        f"**Generated:** {datetime.now(timezone.utc).isoformat()}  ",
        f"**Model:** Financial Advisor AI  ",
        f"",
        f"---",
        f"",
        f"## 1. Executive Summary",
        f"",
        f"{summary}",
        f"",
        f"**Key Takeaway:** {ticker.upper()} is rated **{rec}** with {conf}% confidence. "
            f"Valuation model suggests a blended target of **${m_target}**, "
            f"representing a **{m_mos}% margin of safety** from current levels.",
        f"",
        f"---",
        f"",
        f"## 2. Investment Thesis",
        f"",
        f"### 2.1 Catalysts",
        f"- Earnings momentum score: **{e_score}/100** ({e_verdict})",
    ]
    
    if e_history:
        lines.append(f"- Recent EPS surprise: **{e_history[0].get('surprise_pct', 0):+.1f}%**")
        lines.append(f"- Next earnings date: **{earnings.get('next_earnings_date', 'N/A')}**")
    
    lines.extend([
        f"",
        f"### 2.2 Valuation",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Current Price | ${comps.get('current_price', 'N/A')} |",
        f"| DCF Intrinsic Value | ${dcf.get('intrinsic_per_share', 'N/A')} |",
        f"| Comparable Implied | ${comps.get('implied_price_pe', 'N/A')} |",
        f"| Blended Target | ${m_target} |",
        f"| Margin of Safety | {m_mos}% |",
        f"| Verdict | {m_verdict} |",
        f"",
        f"### 2.3 Key Metrics Snapshot",
    ])
    
    for k, v in list(metrics.items())[:8]:
        lines.append(f"- **{k.replace('_', ' ').title()}:** {v}")
    
    lines.extend([
        f"",
        f"---",
        f"",
        f"## 3. Risks",
        f"",
    ])
    
    if k_flags:
        for flag in k_flags:
            lines.append(f"- ⚠️ {flag}")
    else:
        lines.append(f"- No material compliance flags detected.")
    
    if m_mos < 5:
        lines.append(f"- ⚠️ Low margin of safety — limited downside protection")
    if conf < 60:
        lines.append(f"- ⚠️ Low confidence score ({conf}%) — uncertain conviction")
    
    lines.extend([
        f"",
        f"---",
        f"",
        f"## 4. Compliance Screening",
        f"",
        f"- **Overall Risk Level:** {ky}",
        f"- **Compliance Score:** {k_score}/100",
        f"- **Sanctions Risk:** {kyc.get('sanctions_risk', 'N/A')}/10",
        f"- **ESG Score:** {kyc.get('esg_score', 'N/A')}/100",
        f"- **Controversies:** {kyc.get('controversy_count', 0)}",
        f"",
        f"---",
        f"",
        f"## 5. Strategy Classification",
        f"",
        f"**Primary Strategy:** {strategy}",
        f"",
        f"This position is classified under the **{strategy}** strategy bucket. "
            f"Portfolio construction rules will apply sector limits and position sizing accordingly.",
        f"",
        f"---",
        f"",
        f"## 6. Sources \u0026 References",
    ])
    
    sources = research.get("sources", [])
    for src in sources:
        lines.append(f"- {src}")
    
    lines.extend([
        f"",
        f"---",
        f"",
        f"*This memo was auto-generated by the Stock Command Center Financial Advisor system. "
            f"It combines real market data, earnings analysis, financial modeling, and compliance screening. "
            f"Not investment advice.*",
    ])
    
    return "\n".join(lines)


def run(args) -> bool:
    ticker = args.ticker.upper()
    
    def _load(path):
        p = Path(path)
        if p.exists():
            with open(p, "r", encoding="utf-8") as f:
                return json.load(f)
        return {}
    
    research = _load(args.research)
    earnings = _load(args.earnings)
    model = _load(args.model)
    kyc = _load(args.kyc)
    
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    memo = generate_pitchbook(ticker, research, earnings, model, kyc)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(memo)
    
    print(f"Pitchbook for {ticker}: {output_path}")
    return True


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--ticker", required=True)
    p.add_argument("--research", required=True)
    p.add_argument("--earnings", required=True)
    p.add_argument("--model", required=True)
    p.add_argument("--kyc", required=True)
    p.add_argument("--output", required=True)
    args = p.parse_args()
    sys.exit(0 if run(args) else 1)
